### ISSUE TITLE
Can we configure to ignore gradle-wrapper.jar binary artifacts?

### ISSUE THREAD

**Issue by trask** [open-telemetry/.allstar#6]
Related:
* https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/10425
* https://github.com/ossf/allstar/pull/176
* https://github.com/ossf/allstar/issues/242#issuecomment-1194641312

**Comment by jeffmendoza** [comment]
This is easy to do at the org level. Example:
https://github.com/google/allstar-config/blob/main/binary_artifacts.yaml#L5-L6
